<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="LiteDB" Version="6.0.0-prerelease.73" />
    <PackageReference Include="PowerShellStandard.Library" Version="5.1.1" />
  </ItemGroup>
  <Target Name="PostBuild" AfterTargets="PostBuildEvent">
    <Exec Command="pwsh -nop -c Invoke-Build publish -Configuration $(Configuration)" />
  </Target>
</Project>
